<?php
require_once __DIR__.'/config.php';require_once __DIR__.'/includes/messages.php';require_once __DIR__.'/includes/social.php';
$me=require_login();$to=find_user_by_handle((string)($_GET['to']??''));if(!$to||((int)$to['id']===(int)$me['id'])){http_response_code(404);exit('Пользователь не найден.');}$toId=(int)$to['id'];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){check_csrf();if(!rate_limit('private_message',3,5))$error='Слишком часто. Подождите немного.';else{try{send_private_message((int)$me['id'],$toId,(string)($_POST['text']??''));notifications_add($toId,'message','Новое личное сообщение от @'.($me['handle']??$me['username']??'Пользователь'),'message.php?to='.rawurlencode((string)($me['handle']??$me['username'])));header('Location: message.php?to='.rawurlencode((string)($to['handle']??$to['username'])));exit;}catch(Throwable $e){$error=$e->getMessage();}}}
mark_conversation_read((int)$me['id'],$toId);$rows=conversation_rows((int)$me['id'],$toId);$title='Переписка с @'.($to['handle']??$to['username']).' — GREFFRLEND';include __DIR__.'/includes/header.php';
?>
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><div><h1 style="margin:0">💬 <?=e($to['username']??'Пользователь')?></h1><div class="username">@<?=e((string)($to['handle']??$to['username']??''))?></div></div><a class="btn" href="<?=e(SITE_URL.'/'.rawurlencode((string)($to['handle']??$to['username']??'')))?>">Профиль</a></div></div>
<?php if($error):?><div class="card danger"><?=e($error)?></div><?php endif; ?>
<div class="card" style="max-height:60vh;overflow:auto"><?php if(!$rows):?><p class="muted">Сообщений пока нет. Начните переписку.</p><?php else:foreach($rows as $m):$mine=(int)($m['from']??0)===(int)$me['id'];?><div style="display:flex;justify-content:<?=$mine?'flex-end':'flex-start'?>;margin:10px 0"><div style="max-width:78%;padding:11px 14px;border-radius:13px;background:<?=$mine?'#28150b':'#181818'?>;border:1px solid #33271f"><div style="white-space:pre-wrap;overflow-wrap:anywhere"><?=e(message_decrypt((string)($m['body']??'')))?></div><small class="muted"><?=e((string)($m['created_at']??''))?></small></div></div><?php endforeach;endif;?></div>
<div class="card form"><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><label>Сообщение</label><textarea name="text" maxlength="5000" rows="4" required></textarea><button class="btn" type="submit">Отправить</button></form></div>
<?php include __DIR__.'/includes/footer.php'; ?>