<?php
require_once __DIR__.'/config.php';
require_once __DIR__.'/includes/social.php';
require_once __DIR__.'/includes/economy.php';
$id=(int)($_GET['id']??0);$handle=trim((string)($_GET['handle']??''));$profile=null;$users=data_load('users.json');
if($handle!==''){$wanted=strtolower(ltrim($handle,'@'));foreach($users as $item)if(strtolower((string)($item['handle']??$item['username']??''))===$wanted){$profile=$item;break;}}
elseif($id>0){foreach($users as $item)if((int)($item['id']??0)===$id){$profile=$item;break;}}
if(!$profile){http_response_code(404);exit('Пользователь не найден');}
$profileHandle=(string)($profile['handle']??$profile['username']??'');$id=(int)$profile['id'];if($handle===''&&$profileHandle!==''){header('Location: '.SITE_URL.'/'.rawurlencode($profileHandle),true,301);exit;}
$me=current_user();if($me&&((int)$me['id']===$id))$profile=$me;
$privacy=$profile['privacy']??['email'=>'nobody','phone'=>'nobody','description'=>'everyone'];$canSeeDescription=($privacy['description']??'everyone')==='everyone'||(($privacy['description']??'')==='members'&&$me)||($me&&(int)$me['id']===$id);$canSeeEmail=$me&&((int)$me['id']===$id||($privacy['email']??'nobody')==='everyone');$canSeePhone=$me&&((int)$me['id']===$id||($privacy['phone']??'nobody')==='everyone');$premium=premium($profile);$title=($profile['username']??'Профиль').' — GREFFRLEND';
$accent=(string)($profile['premium_accent']??'#ff6817');if(!preg_match('/^#[0-9a-fA-F]{6}$/',$accent))$accent='#ff6817';$status=trim((string)($profile['premium_status']??''));$frame=(string)($profile['premium_frame']??'glow');$frameStyle=$premium&&$frame==='soft'?'box-shadow:0 0 28px color-mix(in srgb, '.$accent.' 25%, transparent);':($premium?'box-shadow:0 0 36px color-mix(in srgb, '.$accent.' 45%, transparent);':'');$avatarShape=(string)($profile['premium_avatar_shape']??'circle');$avatarRadius=$avatarShape==='square'?'10px':($avatarShape==='rounded'?'24px':'50%');$cardStyle=(string)($profile['premium_card_style']??'default');$cardClass=$premium&&$cardStyle==='glass'?'premium-card-glass':($premium&&$cardStyle==='accent'?'premium-card-accent':'');$nameStyle=(string)($profile['premium_name_style']??'accent');$nameCss=$premium&&$nameStyle==='glow'?'text-shadow:0 0 14px '.$accent.';':($premium&&$nameStyle==='plain'?'':'color:'.$accent.';');$coverStyle=(string)($profile['premium_cover_style']??'default');$cover=e($profile['cover']??'banners/IMG_20260727_215431_065.jpg');$coverExtra=$premium&&$coverStyle==='glow'?'background-image:linear-gradient(135deg,color-mix(in srgb, '.$accent.' 18%, transparent),transparent 55%),url(\''.$cover.'\');':($premium&&$coverStyle==='dark'?'background-image:linear-gradient(rgba(0,0,0,.35),rgba(0,0,0,.65)),url(\''.$cover.'\');':'background-image:url(\''.$cover.'\');');
$lastActivity=(string)($profile['last_activity']??'');$lastActivityTs=$lastActivity!==''?strtotime($lastActivity):false;$online=$lastActivityTs!==false&&$lastActivityTs>=time()-300;$activityText=$online?'В сети':($lastActivityTs!==false?'Был(а) в сети '.date('d.m.Y в H:i',$lastActivityTs):'Недавно зарегистрирован(а)');$activeFrom=preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',(string)($profile['active_from']??''))?(string)$profile['active_from']:'';$activeTo=preg_match('/^(?:[01]\d|2[0-3]):[0-5]\d$/',(string)($profile['active_to']??''))?(string)$profile['active_to']:'';$created=(string)($profile['created_at']??'');
$threads=data_load('threads.json');$latestPosts=[];foreach($threads as $thread)if((int)($thread['author_id']??0)===$id)$latestPosts[]=$thread;usort($latestPosts,static fn(array $a,array $b):int=>(strtotime((string)($b['created_at']??''))?:0)<=>(strtotime((string)($a['created_at']??''))?:0));$latestPosts=array_slice($latestPosts,0,5);
$giftMap=[];foreach(gifts() as $gift)$giftMap[(int)($gift['id']??0)]=$gift;$receivedGifts=[];foreach(data_load('gift_logs.json') as $giftLog){if((int)($giftLog['to']??0)!==$id)continue;$giftId=(int)($giftLog['gift_id']??0);if(!isset($giftMap[$giftId]))continue;$fromName='Пользователь';foreach($users as $giftUser)if((int)($giftUser['id']??0)===(int)($giftLog['from']??0)){$fromName=(string)$giftUser['username'];break;}$receivedGifts[]=['gift'=>$giftMap[$giftId],'from'=>$fromName,'description'=>(string)($giftLog['description']??''),'time'=>(string)($giftLog['time']??'')];}$receivedGifts=array_reverse($receivedGifts);
include __DIR__.'/includes/header.php';
?>
<style>.premium-card-glass{background:color-mix(in srgb,<?=e($accent)?> 7%,transparent);backdrop-filter:blur(10px);border-color:color-mix(in srgb,<?=e($accent)?> 35%,#333)}.premium-card-accent{border-left:3px solid <?=e($accent)?>;box-shadow:0 4px 18px color-mix(in srgb,<?=e($accent)?> 12%,transparent)}.premium-profile-badge{animation:premiumPulse 2.4s ease-in-out infinite}@keyframes premiumPulse{0%,100%{filter:drop-shadow(0 0 0 transparent)}50%{filter:drop-shadow(0 0 7px <?=e($accent)?>)}}.profile-about-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.profile-about-meta span{padding:7px 10px;border:1px solid #303030;border-radius:9px;background:#111}@media(max-width:700px){.profile-cover{height:240px!important}.profile-head img{width:68px!important;height:68px!important}.profile-head h1{font-size:22px!important}}</style>
<section class="profile-cover" style="<?=$coverExtra?>;background-size:cover;background-position:center;height:220px;max-height:42vw;border-radius:18px;border:1px solid <?=e($accent)?>;overflow:hidden;<?=$frameStyle?>"><div style="height:100%;padding:22px;display:flex;align-items:flex-end;background:linear-gradient(180deg,transparent 25%,rgba(0,0,0,.9))"><div class="profile-head" style="display:flex;align-items:center;gap:16px"><img class="avatar" src="<?=e($profile['avatar']??'banners/IMG_20260727_215431_065.jpg')?>" alt="Аватар" style="width:82px;height:82px;object-fit:cover;border-radius:<?=e($avatarRadius)?>;border:3px solid <?=e($accent)?>;transform:translateY(10px);<?=$frameStyle?>"><div><h1 style="margin:0;<?=$nameCss?>"><?=e($profile['username'])?><?php if($premium):?> <span class="premium-badge premium-profile-badge">⭐ PREMIUM</span><?php endif;?></h1><div class="username">@<?=e($profileHandle)?></div><?php if($status!==''):?><div class="muted" style="margin-top:5px">💬 <?=e($status)?></div><?php endif;?><div class="muted" style="margin-top:5px"><span style="color:<?=$online?'#42d77d':'#999'?>">●</span> <?=e($activityText)?></div><span class="pill"><?=e($profile['role']??'user')?></span></div></div></div></section>
<div class="profile-stats"><span><b><?=follower_count($id)?></b> подписчиков</span><span><b><?=following_count($id)?></b> подписок</span><span><b><?=count(user_achievements($id))?></b> достижений</span><span><b><?=wallet($profile)?></b> 🪙</span></div>
<?php if($me&&(int)$me['id']!==$id):?><div style="display:flex;gap:10px;flex-wrap:wrap;margin:14px 0 20px"><form method="post" action="follow.php" style="margin:0"><input type="hidden" name="csrf" value="<?=e(csrf())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="return" value="<?=e($profileHandle)?>"><button class="btn" type="submit"><?=is_following((int)$me['id'],$id)?'Отписаться':'Подписаться'?></button></form><a class="btn" href="gifts.php?to=<?=$id?>">🎁 Подарить подарок</a><a class="btn" href="premium.php?gift=<?=$id?>">⭐ Подарить Premium</a><a class="btn" href="message.php?to=<?=e(rawurlencode($profileHandle))?>">💬 Написать сообщение</a><button class="btn" type="button" onclick="copyProfileLink(this,<?=e(json_encode(SITE_URL.'/'.$profileHandle,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT))?>)">🔗 Скопировать ссылку</button></div><?php else:?><div style="display:flex;gap:10px;flex-wrap:wrap;margin:14px 0 20px"><a class="btn" href="premium.php">⭐ Premium</a><button class="btn" type="button" onclick="copyProfileLink(this,<?=e(json_encode(SITE_URL.'/'.$profileHandle,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT))?>)">🔗 Скопировать ссылку</button></div><?php endif;?>
<div class="profile-grid"><section class="card <?=$cardClass?>"><h2>О пользователе</h2><?php if($canSeeDescription):?><p><?=nl2br(e($profile['description']??'Пользователь пока ничего о себе не написал.'))?></p><?php else:?><p class="muted">Описание скрыто настройками конфиденциальности.</p><?php endif;?><div class="profile-about-meta"><span>📅 С нами с <?=e($created!==''?$created:'неизвестно')?></span><?php if($premium&&$activeFrom!==''&&$activeTo!==''):?><span>🕐 Обычно активен: <?=e($activeFrom)?>–<?=e($activeTo)?></span><?php endif;?></div></section><section class="card <?=$cardClass?>"><h2>Информация</h2><?php if($canSeeEmail):?><p>E-mail: <?=e($profile['email'])?></p><?php endif;?><?php if($canSeePhone&&!empty($profile['phone'])):?><p>Телефон: <?=e($profile['phone'])?></p><?php endif;?><?php if(!$canSeeEmail&&!$canSeePhone):?><p class="muted">Личная информация скрыта.</p><?php endif;?><?php if($me&&(int)$me['id']===$id):?><a class="btn" href="settings.php">Настройки профиля</a> <a class="btn" href="achievements.php">Достижения</a><?php endif;?></section></div>
<section class="card <?=$cardClass?>" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><h2 style="margin:0">📝 Последние посты</h2><?php if($latestPosts):?><span class="muted">Показано <?=count($latestPosts)?> последних</span><?php endif;?></div><?php if(!$latestPosts):?><p class="muted">Пользователь пока не создал постов.</p><?php else:?><div style="display:grid;gap:12px;margin-top:14px"><?php foreach($latestPosts as $post):?><a href="thread.php?id=<?= (int)($post['id']??0) ?>" class="card" style="margin:0;text-decoration:none;border-left:3px solid <?=e($accent)?>"><div style="display:flex;justify-content:space-between;gap:10px;align-items:flex-start"><strong><?=e((string)($post['title']??'Без названия'))?></strong><span class="muted" style="font-size:12px;white-space:nowrap"><?=e((string)($post['created_at']??''))?></span></div><p class="muted" style="margin:7px 0 0"><?=e(mb_strimwidth((string)($post['content']??''),0,180,'…','UTF-8'))?></p></a><?php endforeach;?></div><?php endif;?></section>
<section class="card <?=$cardClass?>" style="margin-top:18px"><h2>✨ Premium-фишки</h2><?php if(!$premium):?><p class="muted">⭐ Premium открывает расширенное оформление, темы форума, статус, эффекты профиля и другие возможности.</p><a class="btn" href="premium.php">Открыть Premium</a><?php else:?><div style="display:flex;gap:10px;flex-wrap:wrap"><span class="pill" style="border-color:<?=e($accent)?>;color:<?=e($accent)?>">🎨 Свой акцент</span><span class="pill">🪟 Темы</span><span class="pill">✨ Эффекты</span><span class="pill">💬 Статус</span><span class="pill">🖼 Аватар</span><span class="pill">🌌 Обложка</span></div><p class="muted">Premium активен — оформление профиля можно менять в настройках.</p><?php endif;?></section>
<section class="card <?=$cardClass?>" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap"><h2 style="margin:0">🎁 Подарки</h2><?php if($me&&(int)$me['id']!==$id):?><a class="btn" href="gifts.php?to=<?=$id?>">🎁 Подарить подарок</a><?php endif;?></div><?php if(!$receivedGifts):?><p class="muted">Пока никто не подарил этому пользователю подарок.</p><?php else:?><div class="gift-grid" style="margin-top:14px"><?php foreach($receivedGifts as $received):?><div class="card" style="text-align:center;margin:0;padding:18px"><div style="font-size:42px"><?=e($received['gift']['emoji']??'🎁')?></div><b><?=e($received['gift']['name']??'Подарок')?></b><div class="muted" style="margin-top:6px">От <?=e($received['from'])?></div><?php if($received['description']!==''):?><p style="margin:10px 0 0"><?=nl2br(e($received['description']))?></p><?php endif;?><div class="muted" style="font-size:12px;margin-top:4px"><?=e($received['time'])?></div></div><?php endforeach;?></div><?php endif;?></section>
<script>function copyProfileLink(button,url){const done=()=>{const old=button.textContent;button.textContent='✅ Ссылка скопирована';setTimeout(()=>button.textContent=old,1800)},fallback=()=>{const value=prompt('Скопируйте ссылку',url);if(value!==null)done()};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(url).then(done).catch(fallback);else fallback()}setTimeout(()=>window.location.reload(),15000);</script>
<?php include __DIR__.'/includes/footer.php'; ?>