<?php
declare(strict_types=1);
session_start();

/* GREFFRLEND Forum v2 - self-contained file storage edition. */
const SITE='GREFFRLEND Forum';
const OWNER_EMAIL='admins@greffrlend.fun';
const DATA=__DIR__.'/data/';
const UPLOADS=__DIR__.'/uploads/';
if(!is_dir(DATA)) mkdir(DATA,0750,true);
if(!is_dir(UPLOADS)) mkdir(UPLOADS,0755,true);
foreach(['users','posts','comments','likes','follows','notifications','reports','gifts','wallets','premium','settings'] as $f){$p=DATA.$f.'.json';if(!is_file($p)) file_put_contents($p,'[]');}
function loadj(string $n):array{$v=json_decode((string)@file_get_contents(DATA.$n.'.json'),true);return is_array($v)?$v:[];}
function savej(string $n,array $v):void{$f=fopen(DATA.$n.'.json','c+');flock($f,LOCK_EX);ftruncate($f,0);rewind($f);fwrite($f,json_encode($v,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));fflush($f);flock($f,LOCK_UN);fclose($f);}
function id(array $a):int{$m=0;foreach($a as $x)$m=max($m,(int)($x['id']??0));return $m+1;}
function e(string $s):string{return htmlspecialchars($s,ENT_QUOTES,'UTF-8');}
function me():?array{if(empty($_SESSION['uid']))return null;foreach(loadj('users') as $u)if((int)$u['id']===(int)$_SESSION['uid'])return $u;return null;}
function csrf():string{return $_SESSION['csrf']??=$_SESSION['csrf']??bin2hex(random_bytes(24));}
function check():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Invalid request');}}
function owner():bool{$u=me();return $u&&((int)($u['id']??0)===(int)($_SESSION['owner_id']??0)||strtolower((string)($u['email']??''))===OWNER_EMAIL);}
function go(string $url):never{header('Location: '.$url);exit;}
function notice(string $s):void{$_SESSION['notice']=$s;}
function uid(string $email):?int{foreach(loadj('users') as $u)if(strtolower($u['email'])===strtolower($email))return(int)$u['id'];return null;}
function userby(int $id):?array{foreach(loadj('users') as $u)if((int)$u['id']===$id)return$u;return null;}
function addnote(int $to,string $text,string $url=''):void{$a=loadj('notifications');$a[]=['id'=>id($a),'to'=>$to,'text'=>$text,'url'=>$url,'read'=>false,'at'=>date('c')];savej('notifications',$a);}
function layout(string $title,string $body):void{$u=me();$n=$u?count(array_filter(loadj('notifications'),fn($x)=>(int)$x['to']===(int)$u['id']&&!$x['read'])):0;?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> — <?=SITE?></title><link rel="stylesheet" href="style.css"></head><body><header><a class="brand" href="?">GREFFRLEND</a><nav><a href="?">Форум</a><a href="?p=search">Поиск</a><?php if($u):?><a href="?p=notifications">🔔 <?=$n?:''?></a><a href="?p=profile&id=<?=$u['id']?>">@<?=e($u['username'])?></a><a href="?p=logout">Выйти</a><?php else:?><a href="?p=login">Войти</a><a class="accent" href="?p=register">Регистрация</a><?php endif;?></nav></header><main><?=$body?></main><footer><img src="../banners/IMG_20260727_215431_065.jpg" alt="GREFFRLEND"><div><a href="?p=rules">Правила</a><a href="?p=offer">Оферта</a><a href="?p=privacy">Конфиденциальность</a><a href="?p=contact">Контакты</a></div><small>© 2025 — 2026 GREFFRLEND. Все права защищены.</small></footer></body></html><?php}
function require_login():array{$u=me();if(!$u)go('?p=login');return$u;}
$p=$_GET['p']??'home';
if($p==='logout'){session_destroy();go('?');}
if($p==='register'&&$_SERVER['REQUEST_METHOD']==='POST'){check();$name=trim($_POST['username']??'');$email=trim($_POST['email']??'');$pass=$_POST['password']??'';$us=loadj('users');if(strlen($name)<3||strlen($pass)<8||!filter_var($email,FILTER_VALIDATE_EMAIL)){notice('Проверьте данные.');go('?p=register');}foreach($us as $x)if(strtolower($x['email'])===strtolower($email)||strtolower($x['username'])===strtolower($name)){notice('Пользователь уже существует.');go('?p=register');}$u=['id'=>id($us),'username'=>$name,'email'=>$email,'password'=>password_hash($pass,PASSWORD_DEFAULT),'role'=>strtolower($email)===OWNER_EMAIL?'owner':'user','bio'=>'','avatar'=>'','background'=>'','created'=>date('c')];$us[]=$u;savej('users',$us);$_SESSION['uid']=$u['id'];if($u['role']==='owner')$_SESSION['owner_id']=$u['id'];notice('Аккаунт создан.');go('?p=profile&id='.$u['id']);}
if($p==='login'&&$_SERVER['REQUEST_METHOD']==='POST'){check();$email=trim($_POST['email']??'');$pass=$_POST['password']??'';foreach(loadj('users') as $u)if(strtolower($u['email'])===strtolower($email)&&password_verify($pass,$u['password'])){$_SESSION['uid']=$u['id'];if($u['role']==='owner')$_SESSION['owner_id']=$u['id'];go('?');}notice('Неверный E-mail или пароль.');go('?p=login');}
if($p==='create'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$title=trim($_POST['title']??'');$text=trim($_POST['text']??'');if($title===''||$text===''){notice('Заполните заголовок и текст.');go('?p=create');}$posts=loadj('posts');$posts[]=['id'=>id($posts),'author'=>$u['id'],'title'=>mb_substr($title,0,160),'text'=>mb_substr($text,0,20000),'category'=>trim($_POST['category']??'Minecraft'),'likes'=>0,'pinned'=>false,'created'=>date('c'),'edited'=>false];savej('posts',$posts);go('?p=post&id='.end($posts)['id']);}
if($p==='like'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$pid=(int)($_POST['id']??0);$likes=loadj('likes');$found=null;foreach($likes as $k=>$l)if((int)$l['post']===$pid&&(int)$l['user']===$u['id'])$found=$k;if($found!==null){unset($likes[$found]);$likes=array_values($likes);}else{$likes[]=['id'=>id($likes),'post'=>$pid,'user'=>$u['id'],'at'=>date('c')];$post=array_values(array_filter(loadj('posts'),fn($x)=>(int)$x['id']===$pid))[0]??null;if($post&&$post['author']!=$u['id'])addnote((int)$post['author'],'@'.$u['username'].' поставил лайк на ваш пост.','?p=post&id='.$pid);}savej('likes',$likes);go('?p=post&id='.$pid);}
if($p==='comment'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$pid=(int)($_POST['post']??0);$text=trim($_POST['text']??'');$parent=(int)($_POST['parent']??0);if($text!==''){ $a=loadj('comments');$a[]=['id'=>id($a),'post'=>$pid,'author'=>$u['id'],'parent'=>$parent,'text'=>mb_substr($text,0,10000),'created'=>date('c')];savej('comments',$a);$post=array_values(array_filter(loadj('posts'),fn($x)=>(int)$x['id']===$pid))[0]??null;if($post&&$post['author']!=$u['id'])addnote((int)$post['author'],'@'.$u['username'].' оставил комментарий.','?p=post&id='.$pid);}go('?p=post&id='.$pid);}
if($p==='follow'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$to=(int)($_POST['id']??0);if($to!==$u['id']){$a=loadj('follows');$idx=null;foreach($a as $k=>$x)if((int)$x['from']===$u['id']&&(int)$x['to']===$to)$idx=$k;if($idx===null){$a[]=['id'=>id($a),'from'=>$u['id'],'to'=>$to,'at'=>date('c')];addnote($to,'@'.$u['username'].' подписался на вас.','?p=profile&id='.$u['id']);}else{unset($a[$idx]);$a=array_values($a);}savej('follows',$a);}go('?p=profile&id='.$to);}
if($p==='report'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$a=loadj('reports');$a[]=['id'=>id($a),'user'=>$u['id'],'post'=>(int)$_POST['post'],'reason'=>mb_substr(trim($_POST['reason']??''),0,1000),'status'=>'new','at'=>date('c')];savej('reports',$a);notice('Жалоба отправлена владельцу форума.');go('?p=post&id='.(int)$_POST['post']);}
if($p==='admin'&&$_SERVER['REQUEST_METHOD']==='POST'&&owner()){check();$act=$_POST['act']??'';$pid=(int)($_POST['id']??0);$posts=loadj('posts');foreach($posts as &$x)if((int)$x['id']===$pid){if($act==='pin')$x['pinned']=!($x['pinned']??false);if($act==='delete')$x['deleted']=true;}unset($x);savej('posts',$posts);go('?p=admin');}
if($p==='profile'&&$_SERVER['REQUEST_METHOD']==='POST'){$u=require_login();check();$users=loadj('users');$id=(int)($_POST['id']??$u['id']);if($id!==$u['id']&&!owner())go('?p=profile&id='.$id);foreach($users as &$x)if((int)$x['id']===$id){$x['bio']=mb_substr(trim($_POST['bio']??$x['bio']),0,1000);$x['background']=mb_substr(trim($_POST['background']??$x['background']),0,500);$x['avatar']=mb_substr(trim($_POST['avatar']??$x['avatar']),0,500);}unset($x);savej('users',$users);go('?p=profile&id='.$id);}
if($p==='post'){$pid=(int)($_GET['id']??0);$posts=loadj('posts');$post=null;foreach($posts as $x)if((int)$x['id']===$pid)$post=$x;if(!$post||!empty($post['deleted'])){http_response_code(404);layout('Не найдено','<section class="card"><h1>Пост не найден</h1><a href="?">Вернуться на форум</a></section>');exit;}$author=userby((int)$post['author']);$likes=count(array_filter(loadj('likes'),fn($x)=>(int)$x['post']===$pid));$liked=me()&&count(array_filter(loadj('likes'),fn($x)=>(int)$x['post']===$pid&&(int)$x['user']===(int)me()['id']));$comments=array_values(array_filter(loadj('comments'),fn($x)=>(int)$x['post']===$pid));$body='<article class="card"><div class="muted">'.e($post['category']).' · '.e($post['created']).'</div><h1>'.e($post['title']).'</h1><div class="author"><a href="?p=profile&id='.$author['id'].'">@'.e($author['username']).'</a></div><p class="posttext">'.nl2br(e($post['text'])).'</p><div class="actions">'.(me()?'<form method="post" action="?p=like"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id" value="'.$pid.'"><button>❤️ '.($liked?'Убрать лайк':'Лайк').' '.$likes.'</button></form>':'❤️ '.$likes).'<a href="#comments">💬 '.count($comments).'</a><form method="post" action="?p=report"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="post" value="'.$pid.'"><input name="reason" placeholder="Причина жалобы"><button>🚩</button></form></div></article><section id="comments"><h2>Комментарии</h2>';foreach($comments as $c){$ca=userby((int)$c['author']);$body.='<div class="comment" style="margin-left:'.min(40,(int)$c['parent']*18).'px"><a href="?p=profile&id='.$ca['id'].'">@'.e($ca['username']).'</a><span class="muted"> '.e($c['created']).'</span><p>'.nl2br(e($c['text'])).'</p>'.(me()?'<details><summary>Ответить</summary><form method="post" action="?p=comment"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="post" value="'.$pid.'"><input type="hidden" name="parent" value="'.$c['id'].'"><textarea name="text" required></textarea><button>Ответить</button></form></details>':'').'</div>';}$body.=(me()?'<form class="card" method="post" action="?p=comment"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="post" value="'.$pid.'"><textarea name="text" maxlength="10000" placeholder="Написать комментарий..." required></textarea><button class="accent">Отправить</button></form>':'<p class="muted">Войдите, чтобы комментировать.</p>').'</section>';layout($post['title'],$body);exit;}
if($p==='profile'){$id=(int)($_GET['id']??(me()['id']??0));$u=userby($id);if(!$u){http_response_code(404);layout('404','<section class="card"><h1>Пользователь не найден</h1></section>');exit;}$posts=array_values(array_filter(loadj('posts'),fn($x)=>(int)$x['author']===$id&&!($x['deleted']??false)));$followers=count(array_filter(loadj('follows'),fn($x)=>(int)$x['to']===$id));$following=count(array_filter(loadj('follows'),fn($x)=>(int)$x['from']===$id));$isf=me()&&count(array_filter(loadj('follows'),fn($x)=>(int)$x['from']===(int)me()['id']&&(int)$x['to']===$id));$premium=array_values(array_filter(loadj('premium'),fn($x)=>(int)$x['user']===$id&&(!$x['until']||strtotime($x['until'])>time())));$body='<section class="profile card"><div class="cover" style="background-image:url('.e($u['background']?:'../banners/IMG_20260727_215431_065.jpg').')"></div><div class="avatar">'.($u['avatar']?'<img src="'.e($u['avatar']).'">':'👤').'</div><h1>@'.e($u['username']).' '.($premium?'⭐':'').'</h1><p>'.nl2br(e($u['bio']?:'Описание пока не заполнено.')).'</p><div class="stats"><b>'.count($posts).'<small>постов</small></b><b>'.$followers.'<small>подписчиков</small></b><b>'.$following.'<small>подписок</small></b></div>'.(me()&&me()['id']!==$id?'<form method="post" action="?p=follow"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id" value="'.$id.'"><button class="accent">'.($isf?'Отписаться':'Подписаться').'</button></form>':'').(me()&&((int)me()['id']===$id||owner())?'<form method="post" action="?p=profile" class="settings"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id" value="'.$id.'"><input name="avatar" placeholder="URL аватара" value="'.e($u['avatar']).'"><input name="background" placeholder="URL фона" value="'.e($u['background']).'"><textarea name="bio" placeholder="Описание">'.e($u['bio']).'</textarea><button>Сохранить профиль</button></form>':'').'</section>';layout('Профиль @'.$u['username'],$body);exit;}
if($p==='notifications'){$u=require_login();$a=loadj('notifications');$out=[];foreach($a as &$x)if((int)$x['to']===$u['id']){$out[]=$x;$x['read']=true;}unset($x);savej('notifications',$a);$body='<section class="card"><h1>Уведомления</h1>';foreach(array_reverse($out) as $x)$body.='<div class="notice">'.e($x['text']).' <a href="'.e($x['url']?:'?').'">Открыть</a><small>'.e($x['at']).'</small></div>';$body.='</section>';layout('Уведомления',$body);exit;}
if($p==='admin'){if(!owner()){http_response_code(403);layout('403','<section class="card"><h1>Доступ запрещён</h1></section>');exit;}$posts=loadj('posts');$reports=loadj('reports');$body='<section class="card"><h1>👑 Панель владельца</h1><p>Постов: '.count($posts).' · Жалоб: '.count($reports).' · Пользователей: '.count(loadj('users')).'</p>';foreach($reports as $r)$body.='<div class="notice">🚩 Пост #'.$r['post'].' — '.e($r['reason']).'</div>';foreach(array_reverse($posts) as $x)if(empty($x['deleted']))$body.='<div class="adminrow"><b>#'.$x['id'].' '.e($x['title']).'</b><form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="id" value="'.$x['id'].'"><button name="act" value="pin">'.(!empty($x['pinned'])?'Открепить':'Закрепить').'</button><button name="act" value="delete">Удалить</button></form></div>'; $body.='</section>';layout('Админ-панель',$body);exit;}
if($p==='create'){$u=require_login();layout('Новый пост','<section class="card"><h1>Новый пост</h1><form method="post" action="?p=create"><input type="hidden" name="csrf" value="'.csrf().'"><input name="title" maxlength="160" placeholder="Заголовок" required><select name="category"><option>Minecraft</option><option>Сервер</option><option>Обновления</option><option>Новости</option><option>Помощь</option><option>Общение</option></select><textarea name="text" maxlength="20000" placeholder="Текст поста" required></textarea><button class="accent">Опубликовать</button></form></section>');exit;}
if($p==='search'){$q=trim($_GET['q']??'');$body='<section class="card"><h1>Поиск</h1><form><input type="hidden" name="p" value="search"><input name="q" value="'.e($q).'" placeholder="Поиск по постам"><button>Искать</button></form>';if($q!=='')foreach(loadj('posts') as $x)if(empty($x['deleted'])&&(mb_stripos($x['title'],$q)!==false||mb_stripos($x['text'],$q)!==false))$body.='<div class="result"><a href="?p=post&id='.$x['id'].'"><b>'.e($x['title']).'</b></a><p>'.e(mb_substr($x['text'],0,180)).'</p></div>';$body.='</section>';layout('Поиск',$body);exit;}
if(in_array($p,['rules','offer','privacy','contact'],true)){ $texts=['rules'=>'<h1>Правила сообщества</h1><p>Уважайте участников. Запрещены спам, вредоносные файлы, травля, мошенничество и обход наказаний. Модерация вправе скрывать нарушающий правила контент. Обжалование наказаний рассматривается владельцем форума.</p>','offer'=>'<h1>Оферта</h1><p>Используя форум, вы соглашаетесь соблюдать правила сообщества. Пользователь отвечает за публикуемый контент. Администрация может изменять правила и удалять нарушения.</p>','privacy'=>'<h1>Конфиденциальность</h1><p>Форум хранит данные, необходимые для аккаунта, безопасности и модерации. Данные не публикуются без предусмотренных настройками оснований.</p>','contact'=>'<h1>Контакты</h1><p>Почта форума: <a href="mailto:admins@greffrlend.fun">admins@greffrlend.fun</a></p>'];layout(ucfirst($p),'<section class="card">'.$texts[$p].'</section>');exit;}
if($p==='register'||$p==='login'){ $reg=$p==='register';$body='<section class="card auth"><h1>'.($reg?'Регистрация':'Вход').'</h1><form method="post"><input type="hidden" name="csrf" value="'.csrf().'">'.($reg?'<input name="username" placeholder="Никнейм" required>':'').'<input type="email" name="email" placeholder="E-mail" required><input type="password" name="password" placeholder="Пароль" required><button class="accent">'.($reg?'Создать аккаунт':'Войти').'</button></form></section>';layout($reg?'Регистрация':'Вход',$body);exit;}
$posts=array_values(array_filter(loadj('posts'),fn($x)=>empty($x['deleted'])));usort($posts,fn($a,$b)=>(int)!empty($b['pinned'])<=>(int)!empty($a['pinned'])?:strcmp($b['created'],$a['created']));$body='<section class="hero"><div><span>GREFFRLEND</span><h1>Форум сервера</h1><p>Общайтесь, публикуйте посты и следите за обновлениями.</p></div>'.(me()?'<a class="accent big" href="?p=create">+ Новый пост</a>':'').'</section><section class="card"><div class="topline"><h2>Лента</h2>'.(owner()?'<a href="?p=admin">👑 Админ-панель</a>':'').'</div>';if(!$posts)$body.='<p class="muted">Пока нет постов.</p>';foreach($posts as $x){$a=userby((int)$x['author']);$likes=count(array_filter(loadj('likes'),fn($l)=>(int)$l['post']===$x['id']));$body.='<article class="post '.(!empty($x['pinned'])?'pinned':'').'">'.(!empty($x['pinned'])?'<b>📌 Закреплено</b>':'').'<h2><a href="?p=post&id='.$x['id'].'">'.e($x['title']).'</a></h2><div class="muted">'.e($x['category']).' · <a href="?p=profile&id='.$a['id'].'">@'.e($a['username']).'</a> · ❤️ '.$likes.'</div><p>'.e(mb_substr($x['text'],0,260)).'</p></article>';}$body.='</section>';layout('Главная',$body);