<?php
require __DIR__.'/../config.php';
$me=user();if(!can_admin($me)){http_response_code(403);exit('Доступ запрещён');}$pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'&&csrf_ok()){
 $id=(int)($_POST['user_id']??0);$action=$_POST['mod_action']??'';$reason=trim($_POST['reason']??'Без указания причины');$days=(int)($_POST['days']??0);$until=$days>0?time()+$days*86400:0;
 $st=$pdo->prepare('SELECT * FROM users WHERE id=?');$st->execute([$id]);$target=$st->fetch();
 if($target&&$target['id']!=$me['id']){
  if($action==='ban'){$pdo->prepare('UPDATE users SET banned_until=?,ban_reason=?,ban_ip=0 WHERE id=?')->execute([$until?:2147483647,$reason,$id]);$pdo->prepare('INSERT INTO moderation_log(moderator_id,target_user_id,action,reason,until_at,created_at)VALUES(?,?,?,?,?,?)')->execute([$me['id'],$id,'Бан',$reason,$until?:2147483647,time()]);}
  if($action==='ban_ip'){$ip=$target['last_ip_hash'];if($ip){$pdo->prepare('INSERT OR REPLACE INTO ip_bans(ip_hash,until_at,reason,created_at)VALUES(?,?,?,?)')->execute([$ip,$until?:2147483647,$reason,time()]);$pdo->prepare('UPDATE users SET ban_ip=1 WHERE id=?')->execute([$id]);$pdo->prepare('INSERT INTO moderation_log(moderator_id,target_user_id,action,reason,until_at,created_at)VALUES(?,?,?,?,?,?)')->execute([$me['id'],$id,'IP-бан',$reason,$until?:2147483647,time()]);}}
  if($action==='ban_both'){$pdo->prepare('UPDATE users SET banned_until=?,ban_reason=?,ban_ip=1 WHERE id=?')->execute([$until?:2147483647,$reason,$id]);$ip=$target['last_ip_hash'];if($ip)$pdo->prepare('INSERT OR REPLACE INTO ip_bans(ip_hash,until_at,reason,created_at)VALUES(?,?,?,?)')->execute([$ip,$until?:2147483647,$reason,time()]);$pdo->prepare('INSERT INTO moderation_log(moderator_id,target_user_id,action,reason,until_at,created_at)VALUES(?,?,?,?,?,?)')->execute([$me['id'],$id,'Бан + IP-бан',$reason,$until?:2147483647,time()]);}
  if($action==='unban'){$pdo->prepare('UPDATE users SET banned_until=NULL,ban_reason=NULL,ban_ip=0 WHERE id=?')->execute([$id]);if($target['last_ip_hash'])$pdo->prepare('DELETE FROM ip_bans WHERE ip_hash=?')->execute([$target['last_ip_hash']]);$pdo->prepare('INSERT INTO moderation_log(moderator_id,target_user_id,action,reason,created_at)VALUES(?,?,?,?,?)')->execute([$me['id'],$id,'Снятие бана','Администратор снял наказание',time()]);}
 }
 header('Location: /admin/');exit;
}
$users=$pdo->query('SELECT * FROM users ORDER BY id DESC LIMIT 100')->fetchAll();$threads=(int)$pdo->query('SELECT COUNT(*) FROM threads')->fetchColumn();$replies=(int)$pdo->query('SELECT COUNT(*) FROM replies')->fetchColumn();$logs=$pdo->query('SELECT l.*,m.username moderator,u.username target FROM moderation_log l JOIN users m ON m.id=l.moderator_id LEFT JOIN users u ON u.id=l.target_user_id ORDER BY l.id DESC LIMIT 20')->fetchAll();
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Админ-панель — GREFFRLEND</title><link rel="stylesheet" href="/style.css"></head><body><header class="site-header"><div class="wrap nav"><a class="logo" href="/">GREFFRLEND ADMIN</a><a href="/">← Форум</a></div></header><main class="wrap"><section class="hero"><span class="eyebrow">CONTROL CENTER</span><h1>Панель управления</h1><p>Модерация пользователей, наказания и журнал действий.</p></section><div class="section-grid"><div class="info-card"><span>👥</span><h3>Пользователи</h3><p><?=count($users)?> последних</p></div><div class="info-card"><span>💬</span><h3>Темы</h3><p><?=$threads?></p></div><div class="info-card"><span>📝</span><h3>Ответы</h3><p><?=$replies?></p></div></div><div class="section-head"><div><span class="eyebrow">МОДЕРАЦИЯ</span><h2>Пользователи</h2></div></div><div class="forum-list"><?php foreach($users as $u): ?><div class="thread-row"><div class="avatar"><?=e(mb_strtoupper(mb_substr($u['username'],0,1)))?></div><div class="thread-info"><h3><?=e($u['username'])?> <span class="muted">#<?=$u['id']?></span></h3><p><?=e($u['email'])?> · роль: <?=e($u['role'])?> · <?=!empty($u['banned_until'])?'🔴 заблокирован':'🟢 активен'?></p></div><div><details><summary class="button mini">Наказать</summary><form method="post" style="margin-top:10px;display:grid;gap:7px;min-width:220px"><?=csrf_field()?><input type="hidden" name="user_id" value="<?=$u['id']?>"><select name="mod_action" style="background:#0b0b0b;color:#fff;padding:9px;border:1px solid #333;border-radius:8px"><option value="ban_both">Бан + IP</option><option value="ban">Бан аккаунта</option><option value="ban_ip">IP-бан</option><option value="unban">Снять бан</option></select><select name="days" style="background:#0b0b0b;color:#fff;padding:9px;border:1px solid #333;border-radius:8px"><option value="1">1 день</option><option value="3">3 дня</option><option value="7">7 дней</option><option value="14">14 дней</option><option value="30">30 дней</option><option value="0">Навсегда</option></select><input name="reason" placeholder="Причина" required><button class="button mini">Применить</button></form></details></div></div><?php endforeach;?></div><div class="section-head"><div><span class="eyebrow">AUDIT LOG</span><h2>Последние действия</h2></div></div><div class="forum-list"><?php foreach($logs as $l): ?><div class="thread-row"><div class="thread-icon">⚙</div><div class="thread-info"><h3><?=e($l['action'])?></h3><p><?=e($l['moderator'])?> → <?=e($l['target']??'удалённый пользователь')?> · <?=e($l['reason']??'')?></p></div><div class="muted"><?=date('d.m.Y H:i',$l['created_at'])?></div></div><?php endforeach;?></div></main></body></html>