<?php
require_once __DIR__.'/../config.php';require_once __DIR__.'/../includes/messages.php';
$owner=require_owner();$users=data_load('users.json');$selectedA=(int)($_GET['a']??0);$selectedB=(int)($_GET['b']??0);
if($selectedA>0&&$selectedB>0){$ua=find_user_by_id($selectedA);$ub=find_user_by_id($selectedB);if($ua&&$ub){$rows=conversation_rows($selectedA,$selectedB);log_action('Просмотр личной переписки',$ua['username'].' ↔ '.$ub['username'],'Только для передачи по требованию суда/уполномоченного органа.');}}
$title='Личные переписки — GREFFRLEND';include __DIR__.'/../includes/header.php';
?>
<div class="card"><h1>👑 Личные переписки</h1><p class="muted">Доступ только владельцу. Просмотр предназначен исключительно для законного запроса/передачи материалов в рамках суда или иного уполномоченного производства.</p></div>
<?php if($selectedA>0&&$selectedB>0&&isset($rows)):?><div class="card"><h2><?=e($ua['username'])?> ↔ <?=e($ub['username'])?></h2><?php if(!$rows):?><p class="muted">Переписка пуста.</p><?php else:foreach($rows as $m):$from=find_user_by_id((int)($m['from']??0));?><div style="padding:12px;margin:9px 0;border:1px solid #302820;border-radius:10px"><b><?=e($from['username']??'Пользователь')?></b><span class="muted"> · <?=e((string)($m['created_at']??''))?></span><div style="white-space:pre-wrap;margin-top:6px"><?=e(message_decrypt((string)($m['body']??'')))?></div></div><?php endforeach;endif;?></div><?php endif;?>
<h2>Переписки</h2>
<?php $seen=[];foreach(conversation_participants_for_admin() as $pair):$key=$pair[0].'_'.$pair[1];if(isset($seen[$key]))continue;$seen[$key]=1;$a=find_user_by_id($pair[0]);$b=find_user_by_id($pair[1]);if(!$a||!$b)continue;?><div class="card" style="display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap"><b><?=e($a['username'])?> ↔ <?=e($b['username'])?></b><a class="btn" href="messages.php?a=<?=$pair[0]?>&b=<?=$pair[1]?>">Просмотреть</a></div><?php endforeach;?>
<?php include __DIR__.'/../includes/footer.php'; ?>