<?php require_once __DIR__.'/../config.php'; require_once __DIR__.'/social.php'; $me=current_user(); $title=$title??SITE_NAME; $adminPage=str_contains(str_replace('\\','/',$_SERVER['REQUEST_URI']??''),'/admin/'); ?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?></title><meta name="description" content="Официальный форум GREFFRLEND"><meta name="robots" content="index,follow"><link rel="stylesheet" href="<?=e(SITE_URL)?>/style.css?v=20260825-2"><?php if($adminPage): ?><link rel="stylesheet" href="<?=e(SITE_URL)?>/admin/admin.css?v=20260825-2"><?php endif; ?><style>
*{box-sizing:border-box}html{background:#090909!important;color-scheme:dark}body{margin:0!important;background:#090909!important;color:#eee!important;font:15px/1.65 Arial,sans-serif!important}a{color:#ff7420;text-decoration:none}a:hover{color:#ff382d}.site-header{background:#0c0c0c!important;border-bottom:1px solid #242424!important;position:sticky;top:0;z-index:50}.header-inner,.page,.server-strip,.footer-inner{width:min(1120px,94%);margin:auto}.header-inner{min-height:68px;display:flex;align-items:center;justify-content:space-between;gap:20px}.logo{font-size:27px;font-weight:900;letter-spacing:4px!important;background:linear-gradient(100deg,#ff7a18,#e52b25,#ff7a18)!important;background-size:200% 100%;color:transparent!important;background-clip:text;-webkit-background-clip:text}.main-nav{display:flex;gap:16px;align-items:center;flex-wrap:wrap}.main-nav a{color:#ddd!important;text-decoration:none!important}.main-nav a:hover{color:#ff7420!important}.server-strip{padding:12px 0;display:flex;gap:12px;align-items:center;border-bottom:1px solid #171717;color:#aaa}.server-strip b{color:#fff}.server-strip button,.tool{border:0;background:#171717;color:#ff7420;cursor:pointer;padding:9px 12px;border-radius:8px}.page{padding-top:24px;min-height:65vh}.card{background:#111!important;border:1px solid #272727!important;border-radius:13px;padding:20px;margin:12px 0}.admin-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:15px}.stat{font-size:26px;font-weight:800;color:#ff711c!important}.category{font-size:11px;text-transform:uppercase;letter-spacing:1.7px;color:#ff7620!important;font-weight:800}.muted{color:#8c8c8c!important}.btn{display:inline-block;background:linear-gradient(100deg,#f45d12,#dc2828)!important;color:#fff!important;padding:11px 18px;border-radius:9px;font-weight:700;border:0;cursor:pointer;text-decoration:none}.button-row{display:flex;gap:10px;flex-wrap:wrap}.thread{display:flex;justify-content:space-between;gap:20px}.form input,.form textarea,.form select,input,textarea,select{width:100%;background:#0b0b0b!important;color:#fff!important;border:1px solid #343434!important;border-radius:8px;padding:12px;margin:7px 0 14px}.form textarea{min-height:170px}.site-footer{margin-top:60px;background:#0d0d0d!important;border-top:1px solid #292929!important}.footer-inner{padding:30px 0;display:flex;justify-content:space-between;gap:25px}.footer-links{display:flex;gap:16px;flex-wrap:wrap}.copyright{text-align:center;padding:16px;border-top:1px solid #202020;color:#707070}.site-icon{width:42px!important;height:42px!important;object-fit:cover;border-radius:9px}
<?php if($adminPage): ?>
html,body{background:#080808!important;color:#f2f2f2!important}.page{max-width:1180px!important}.site-header,.site-footer,.server-strip{background:#0b0b0b!important}.card{background:#111!important;border-color:#2a2a2a!important;box-shadow:0 8px 28px rgba(0,0,0,.3)}h1,h2,h3,b,strong{color:#fff!important}.main-nav a{color:#ddd!important}.main-nav a:hover{color:#ff711b!important}.pin{color:#ff711b!important}.small{padding:7px 10px}.admin-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.button-row .btn{box-shadow:0 4px 14px rgba(255,80,0,.12)}
<?php endif; ?>
@media(max-width:760px){.header-inner{align-items:flex-start;flex-direction:column;padding:13px 0}.main-nav{gap:10px}.admin-grid{grid-template-columns:1fr}.thread{flex-direction:column}.footer-inner{flex-direction:column}}
</style></head><body>
<header class="site-header"><div class="header-inner"><a class="logo" href="<?=e(SITE_URL)?>/index.php">GREFFRLEND</a><nav class="main-nav"><a href="<?=e(SITE_URL)?>/index.php">Форум</a><a href="<?=e(SITE_URL)?>/search.php">Поиск</a><a href="<?=e(SITE_URL)?>/recommendations.php">Рекомендации</a><?php if($me):?><a href="<?=e(SITE_URL)?>/notifications.php">🔔<?php $unread=unread_notifications((int)$me['id']);if($unread):?><span class="notif-badge"><?=e((string)$unread)?></span><?php endif;?></a><a href="<?=e(SITE_URL)?>/profile.php?id=<?=$me['id']?>"><?=e($me['username'])?></a><?php if(is_admin($me)):?><a href="<?=e(SITE_URL)?>/admin/index.php">Админка</a><?php endif;?><?php else:?><a href="<?=e(SITE_URL)?>/login.php">Войти</a><?php endif;?></nav></div></header>
<div class="server-strip"><span>Сервер: <b><?=e(SERVER_IP)?></b></span><button type="button" onclick="copyIP()">Копировать IP</button></div><main class="page">
